// Create a JavaScript function that takes an array of numbers,
// returns an object containing:
// - the sum of all numbers
// - the highest number
// - the lowest number
// Let Copilot generate the entire function.
// Create a JavaScript function that takes an array of numbers,
// and returns an object containing:
// - the sum of all numbers
// - the highest number
// - the lowest number
// Implementation generated by Copilot-style assistant.

/**
 * Analyze an array of numbers and return summary stats.
 * @param {number[]} numbers - Array of numbers to analyze
 * @returns {{sum: number, max: number|null, min: number|null}} Summary object
 */
function analyzeNumbers(numbers) {
	if (!Array.isArray(numbers)) {
		throw new TypeError('Expected an array of numbers');
	}

	if (numbers.length === 0) {
		return { sum: 0, max: null, min: null };
	}

	let sum = 0;
	let max = -Infinity;
	let min = Infinity;

	for (const n of numbers) {
		const num = Number(n);
		if (Number.isNaN(num)) {
			throw new TypeError('Array must contain only numbers');
		}
		sum += num;
		if (num > max) max = num;
		if (num < min) min = num;
	}

	return { sum, max, min };
}

// Export for CommonJS and ES module users
if (typeof module !== 'undefined' && module.exports) {
	module.exports = { analyzeNumbers };
} else {
	try {
		// @ts-ignore
		window.analyzeNumbers = analyzeNumbers;
	} catch (e) {
		/* ignore */
	}
}

export { analyzeNumbers };
